baseURL = 'https://soulfiremage.github.io/Katiya_Starship/'
languageCode = 'en-us'
title = 'Katiya Starship'
theme = 'hugo-texify3'
enableRobotsTXT = true
enableGitInfo = true

[pagination]
pagerSize = 10

[taxonomies]
tags = "tags"
categories = "categories"

[permalinks]
posts = '/posts/:contentbasename/'

[params]
title = "Katiya Starship"
author = "Richard Griffiths"
description = "Katiya Starship - Mathematical adventures and chaos theory explorations"
customCSS = ["css/custom-colors.css"]
footnote = """
Powered by <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = false

  [params.sharingbuttons]
  twitter = true
  email = true
  linkedin = true
  reddit = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    noClasses = false

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Posts'
    url = '/posts'
    weight = 2

[outputs]
home = ["HTML", "RSS"]
